### ISSUE TITLE
Indicate source of a given Series entry on screen.

### ISSUE THREAD

**Issue by rashley-iqt** [CyberReboot/CRviz#274]
### Describe the feature you are requesting
Right now the distinction between data from an upload vs import vs a url is not made clear to the user

### Describe your use case
I can't tell where the data came from without thinking about it.  

### Explain how this feature supports your use case? Other use cases?
I should be able to easily determine where the data came from.

### Additional Info
None

**Comment by gregs5** [comment]
Maybe use some of the space that will be recovered from moving the UPLOAD function into the drop-down menu?
