### ISSUE TITLE
Expand file import functionality to include "generic" JSON

### ISSUE THREAD

**Issue by gregs5** [CyberReboot/CRviz#33]
Currently CRviz requires that within a JSON file upload the JSON is prefaced with:

 `{ "dataset": [` 

I believe this is required for some of the additional filtering/import options when bringing in data from an HTTP-based source.  That said, it would be great if we could introduce some logic that could take a file with the appropriate "dataset" prefixing, but in the absence of that, just assume that the file is stock JSON and attempt to import it as such. (i.e. sans "dataset" reference) 

This is specifically with a local file upload in CRViz - we probably want to keep the URL-based import as-is.

**Comment by rashley-iqt** [comment]
is the vision in this scenario to recieve something like:
`[{
    "uid": "2ad6c248-bea9-4dca-ae74-0212c7dea895",
    "mac": "ca:e6:e7:b7:d5:b0",
    "rDNS_host": "tnw785it",
    "subnet": "10.232.208.0/24",
    "record": {
      "source": "nmap",
      "timestamp": "2018-03-22 16:42:53.323174"
    },
    "role": {
      "role": "Internal web server",
      "confidence": 62
    },
    "os": {
      "os": "BSD",
      "confidence": 73
    },
    "IP": "10.232.208.48"
  },]`
Or
`{
    "uid": "2ad6c248-bea9-4dca-ae74-0212c7dea895",
    "mac": "ca:e6:e7:b7:d5:b0",
    "rDNS_host": "tnw785it",
    "subnet": "10.232.208.0/24",
    "record": {
      "source": "nmap",
      "timestamp": "2018-03-22 16:42:53.323174"
    },
    "role": {
      "role": "Internal web server",
      "confidence": 62
    },
    "os": {
      "os": "BSD",
      "confidence": 73
    },
    "IP": "10.232.208.48"
  },`

that is to say, are we expecting an explicit array or just a stream of objects?

**Comment by cglewis** [comment]
yeah, it should expect valid JSON - so the latter would be invalid. and the former would be valid (minus the last comma)

**Comment by rashley-iqt** [comment]
so, in this use case they are relying on the default configuration?  I don't believe that 
`{
     [...],
      "configuration":{...}
  }`
would be considered valid json.

**Comment by cglewis** [comment]
so, currently CRviz expects a valid JSON object that looks like:
```
{ "dataset": [...], "configuration":[...]}
```
where the `configuration` key is optional.

what this proposes is being able to upload a valid JSON file without the need for those keys, and CRviz would do the translation for you.

so for example you could upload something like this:
```
{"foo":"bar"}
```
and it would become:
```
{"dataset":[{"foo":"bar"}]}
```
alternatively you could upload something like this:
```
[{"foo":"bar"},{"baz":"bar"}]
```
and it would become:
```
{"dataset":[{"foo":"bar"},{"baz":"bar"}]}
```

Does that help?

**Comment by rashley-iqt** [comment]
Yes.  That was what I thought the expectation was, but I wanted to verify before I spent a bunch of time implementing.
