### ISSUE TITLE
Display version info in application

### ISSUE THREAD

**Issue by rashley-iqt** [CyberReboot/CRviz#43]
We really should display version info somewhere in the application.  We have it up on github.io and we want  outside users to report issues against it then we really should provide a mechanism for everyone to know what version of the software is being used.

**Comment by gregs5** [comment]
Was thinking about this more - and given @cglewis ' comment about a clear "starting point" - might we want to jam an Info icon to the right of the CRviz logo in the upper right, and have that button gen a pop-up box with: 1) version info, 2) Quick "Start by doing ___" info, and 3) link to project home?

![info-icon](https://user-images.githubusercontent.com/22061293/40427876-ec1a2e5c-5e6c-11e8-86e9-b29a6fc5ed97.png)

**Comment by cglewis** [comment]
that sounds perfect to me @gregs5

**Comment by rashley-iqt** [comment]
i have a PR in that contains code to add the popup.  @lilchurro and I are discussing position.  But I also wanted to put out a call for text.  right now I just have a link to the homepage (https://www.cyberreboot.org/projects/crviz/), the version number, and some copyright text.  It feels a bit sparse, any thoughts?

**Comment by cglewis** [comment]
@rashley-iqt I believe this can be closed now, yes?
