### ISSUE TITLE
Implement search function

### ISSUE THREAD

**Issue by gregs5** [CyberReboot/CRviz#46]
It would be great if we could search on the data once it's loaded.  Minimally I was thinking:

1. Initially scope it to the values of the existing JSON fields (e.g. "10.4.2.7") Let's start simple...
2. A search box in the UI so that one can do a basic string searches of the values
3. Some sort of visual queue that indicates whether results were found or not 
4. Visually highlighting the results in some way
5. Some way of handling the situation where multiple results are found (e.g. Multiple hosts with the same name, or more generically, entities that have duplicate values)

**Comment by rashley-iqt** [comment]
I noticed something interesting yesterday while showing CRViz to Dave, which is that the index build on loading a 50k node NCHS dataset on causes of death takes approximately the same amount of time as the index build on loading our generated 4k node dataset.  I want to generate some datasets with varying widths and depths to see if i can get a better handle on some of our performance issues.  As a side issue to that I need to make the index build asynchronous.
