### ISSUE TITLE
ability to export loaded dataset

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/CRviz#51]
this would be particularly useful when using a URL where you may not already have the JSON file of what you're viewing

**Comment by rashley-iqt** [comment]
just making sure i understand this request, you aren't talking about grouping or any of that.  For instance, if you were to load the "small" dataset do whatever manipulations you wanted and then export you should still end up with an exact copy of the "small" dataset we have on the server?

**Comment by cglewis** [comment]
correct.
