### ISSUE TITLE
when using the URL for the dataset, being able to periodically poll for updates would be a nice addition

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/CRviz#52]
currently, if there are updates to the file that is being fed by a URL selection, you have to refresh the whole page and load the URL in again to get the updated dataset, if there was a polling feature for this that updated the interface with any data updates on some interval, it would be useful for dashboard/HUD setups.

**Comment by gregs5** [comment]
Perhaps obvious, but two additional I'd offer up for consideration: 

1. A periodic update option would be good. Of course, the easiest way to implement is a simple reload of data with the existing display settings. (read: the whole data set gets reloaded)  But...

2. If/when we get there, when we are able to track changes / a delta between two data sets. in the case of periodic (and automatic) reloads if there ARE updates, it might be worth temporarily showing some indicator of the update via the visual change references we've discussed previously.  (e.g. New nodes blink for 15 minutes)

**Comment by rashley-iqt** [comment]
I think the smartest way to approach this is to begin by implementing number 1.  If we start dealing with deltas between sets we will need a manual refresh option anyway, so either way we have to do that work.  Before we can implement number 2, we are going to need to figure out some kind of data storage construct, but once we have that i think it gives a clear path and platform to be able to deal with time series data.

**Comment by cglewis** [comment]
@rashley-iqt agree, I think tracking changes/history/deltas needs to be a larger discussion both from implementation but also from a design perspective.

**Comment by cglewis** [comment]
A nice addition to this would be to retain the current settings that are applied. i.e. group by, coloring, etc.

**Comment by cglewis** [comment]
yup, makes sense.
