### ISSUE TITLE
standardize on either npm or yarn

### ISSUE THREAD

**Issue by rashley-iqt** [CyberReboot/CRviz#68]
currently our dev and docker process involves a mix of npm and yarn. They both do the same general things and it is wasteful and confusing to use both.  I think we need to pick one and go with it.  My intention is to do some research before making a specific suggestion.  Do any team members have a strong opinion one way or the other?

**Comment by cglewis** [comment]
no preference from me.

**Comment by rashley-iqt** [comment]
after digging into it it appears that yarn is much faster than npm, however yarn uses facebook's internal npm registry and may or may not be reporting data back to FB (they say not, but i think Zuckerberg is still on his apology tour from the last time they were sure data didn't get shared that way).  Also yarn has shipped some weird regressions while npm seems to be improving.  My take is that yarn is adding an extra layer of complexity in exchange for some things we don't much need/care about so i vote npm.  @lilchurro ? @gregs5 ?

**Comment by gregs5** [comment]
I think less dependencies are better; I'd vote straight npm.

**Comment by lilchurro** [comment]
You know my vote — if speed of builds is the only advantage, I don’t see much use for having two managers... and would therefore prefer npm.
